### ISSUE TITLE
Recurring payments

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#31]
There are certain transactions (payments) that are repeating from time to time. Some examples of those transactions are monthly internet bill, a Netflix subscription, etc.

Sometimes it's easy to forget some of these recurring payments, especially when there are a bunch of them at the moment.

The goal here is to remove the burden of keeping all these repetitive transactions in mind. The application has to provide a way to create a list of such transactions. That list can play the role of reminders. Also, based on that list the application can suggest filling in a recurring transaction when time is due.

### Sub-tasks

- [x] [Create a `RecurringPayment` model](https://github.com/ck3g/homebugh/issues/61)
- [x] [Add a page to display the list of recurring payments](https://github.com/ck3g/homebugh/issues/63)
- [x] [Add functionality to create recurring payments](https://github.com/ck3g/homebugh/issues/64)
- [x] [Add functionality to edit recurring payments](https://github.com/ck3g/homebugh/issues/65)
- [x] [Add functionality to delete recurring payments](https://github.com/ck3g/homebugh/issues/66)
- [x] [Add `next_payment_on` field](https://github.com/ck3g/homebugh/issues/86)
- [x] [Display the list of due recurring payments above the transactions](https://github.com/ck3g/homebugh/pull/112)
- [x] [Add the ability to skip a due recurring payment (move to the next period)](https://github.com/ck3g/homebugh/issues/102)
- [x] [Add the ability to apply a due recurring payment (create a transaction and move to the next period)](https://github.com/ck3g/homebugh/pull/109)
- [x] [Provide translations for recurring payments](https://github.com/ck3g/homebugh/issues/88)

**Comment by ck3g** [comment]
Done! 🚀
