### ISSUE TITLE
Allow hiding certain accounts from the overall balance

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#32]
At the moment the balance of all accounts (on top of the page) displays funds from all the accounts.

<img width="942" alt="Screenshot 2020-09-28 at 19 15 06" src="https://user-images.githubusercontent.com/123158/94466020-11918f00-01c1-11eb-9e29-ecd0fb9af218.png">

There should be an option to hide some accounts from the balance overview.

- [x] [Create a boolean `show_in_summary` column in the `accounts` table, with the default value of `true`](https://github.com/ck3g/homebugh/issues/57)
- [x] [Allow to set `show_in_summary` value from create account page (`/accounts/new`).](https://github.com/ck3g/homebugh/issues/58)
- [x] [Allow to update `show_in_summary` value on edit account page (`/accounts/:id/edit`).](https://github.com/ck3g/homebugh/issues/59)
- [x] [Accounts summary should display accounts only with `show_in_summary == true`.](https://github.com/ck3g/homebugh/issues/60)

**Comment by ck3g** [comment]
All steps are done
